name: Check code
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust-version: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code into the proper directory
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-version }}

      - name: Check build
        run: cargo build --verbose
